site_name: OpenTenBase Documentation
repo_url: https://github.com/OpenTenBase/docs
repo_name: OpenTenBase/docs
edit_uri: edit/main/docs/

theme:
  name: material

  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  features:
    # - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/logo.svg
  icon:
    repo: fontawesome/brands/github

  markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - admonition
    - pymdownx.details
    - pymdownx.tabbed:
        alternate_style: true 
    - tables
    - attr_list
    - md_in_html

nav:
  - 首页: index.md
  - 用户指南:
    - TBase:
      - 快速入门: guide/01-quickstart.md
      - 应用接入: guide/02-access.md
      - 基本使用: guide/03-basic-use.md
      - 高级使用: guide/04-advanced-use.md
      - 组件安装及管理: guide/05-component.md
      - 主备切换: guide/06-switching.md
      - 用户权限管理: guide/07-user-rights.md
      - 数据导入导出: guide/08-data-dump-restore.md
      - 问题定位及性能优化: guide/09-problem-performance.md
      - V2.3.0升级特性pg_clean使用说明: guide/10-pg_clean.md
      - V2.3.0升级特性pg_unlock使用说明: guide/11-pg_unlock.md
      - V2.3.0升级特性opentenbase_subscription使用说明: guide/12-opentenbase_subscription.md
    - TXSQL:
      - 概述: guide/16-txsql_quickstart.md
      - 安装指南: guide/17-txsql_deploy.md
    - 周边生态:
      - Prometheus/Grafana可视化监控: guide/13-opentenbase_monitoring.md
      - 在kubernetes上运行OpenTenbase: guide/14-kubeblocks-support.md
      - 使用docker构建一个简单集群: guide/15-docker-deploy.md
  - 版本说明:
    - TBase:
      - v2.6.0: release/v2-6-0.md
      - v2.5.0: release/v2-5-0.md
      - v2.4.0: release/v2-4-0.md
      - v2.3.0: release/v2-3-0.md
      - v2.2.0: release/v2-2-0.md
  - 常见问题: 
    - TXSQL常见问题: faq.md
  - 参与贡献:
    - 如何贡献: contribution/how-to.md
    - 文档库格式手册: contribution/docs-format-guide.md
  - 下载: download.md


plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: zh
          default: true
          name: 中文
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
              首页: Home
              用户指南: Guide
              快速入门: Quick Start
              概述: Overview
              安装指南: Deploy
              应用接入: Application Access
              基本使用: Basic Usage
              高级使用: Advanced Usage
              组件安装及管理: Components
              主备切换: Switching
              用户权限管理: User Rights Management
              数据导入导出: Data Dump and Restore
              问题定位及性能优化: Problem tracking and Performance Optimization
              V2.3.0升级特性pg_clean使用说明: V2.3.0 Feature pg_clean
              V2.3.0升级特性pg_unlock使用说明: V2.3.0 Feature pg_unlock
              V2.3.0升级特性opentenbase_subscription使用说明: V2.3.0 Feature opentenbase_subscription
              版本说明: Releases
              常见问题: FAQ
              参与贡献: Contributing
              如何贡献: How to contribute
              文档库格式手册: Documentation format guide
              下载: Download
              周边生态: Peripheral ecosystem
              Prometheus/Grafana可视化监控: Monitoring visualization with Prometheus/Grafana
              在kubernetes上运行OpenTenbase: Run opentenbase on kubernetes
              使用docker构建一个简单集群: Building simple cluster with docker
              TXSQL常见问题: TXSQL FAQ